//
// Created by timkoffy on 11/11/25.
//

#ifndef PODUSHKAAPPLICATION_MUSICMANAGER_H
#define PODUSHKAAPPLICATION_MUSICMANAGER_H


class musicManager {
};


#endif //PODUSHKAAPPLICATION_MUSICMANAGER_H